name: finance

services:
  app:
    build:
      context: ../
      dockerfile: ./build/Dockerfile.local
    ports:
      - "9000:9000"
    volumes:
      - ../:/app
      - ../.air.toml:/app/.air.toml
      - go-mod:/go/pkg/mod
    depends_on:
      postgres:
        condition: service_healthy

  postgres:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - ../.env
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  go-mod:
  postgres_data: