app:
  env: "dev"
  severity: 6
server:
  logger: "debug"
  addr: "0.0.0.0:9000"
  jwt_access_lifetime: "15m"
  jwt_refresh_lifetime: "100h"
postgres:
  host: "postgres"
  port: 5432
  dbname: "finance"
  user: "postgres"
  password: "root"